services:
  - type: web
    name: notes-app
    env: node
    buildCommand: |
      # Install root dependencies
      npm install
      
      # Install frontend dependencies and build
      cd Notes_App/frontend
      npm install --legacy-peer-deps
      npm install -g npm@latest
      npm install --save-dev vite @vitejs/plugin-react
      npm install daisyui --legacy-peer-deps
      npm run build
      
      # Install backend dependencies
      cd ../backend
      npm install --legacy-peer-deps
    startCommand: cd Notes_App/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: notes-app-db
          property: connectionString
    plan: free
