services:
  - type: web
    name: notes-app
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: notes-app-db
          property: connectionString
    plan: free
    build:
      commands:
        - npm install
        - cd Notes_App/frontend && npm install && npm run build
    run:
      command: node Notes_App/backend/src/server.js
