services:
  - type: web
    name: notes-app
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: notes-app-db
          property: connectionString
    plan: free
