services:
  - type: web
    name: notes-app
    env: node
    buildCommand: |
      npm install
      cd Notes_App/frontend
      npm install
      npm install -g npm@latest
      npm install --save-dev vite
      cd ..
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: notes-app-db
          property: connectionString
    plan: free
